<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-windows7.0;netstandard2.0</TargetFrameworks>
    <Platforms>x86</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup Label="NuGet">
    <!-- https://learn.microsoft.com/nuget/reference/msbuild-targets#packing-an-icon-image-file -->
    <None Include="NuGetIcon.png" Pack="true" PackagePath="\" />
    <!-- https://learn.microsoft.com/nuget/reference/msbuild-targets#packagereadmefile -->
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" />
  </ItemGroup>

</Project>
